services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: sebas_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ../../data/rabbitmq:/var/lib/rabbitmq
